%
% /home/astrand/GoogleDrive/unpak-database/database code/unpak-shiny/upload.test/upload-format/body.Rnw
% $Modified:  Fri Feb 20 15:32:06 EST 2015$




<<echo=F,results='hide'>>=
datin <- read.csv("../example-sheet.csv")
columns <- names(datin)
@ 


\section*{Format of upload spreadsheets}

Uploading data in the form of entire spreadsheets requires some pretty
finicky formatting and data checking.  Mostly, getting a spreadsheet
to 'check' for upload requires an iterative approach where you fix
problems the upload checker identifies

\subsection*{Format of spreadsheet file}
\begin{itemize}
\item The spreadsheet has to be in the form of a comma separated value
(*.csv) file.  
\item The spreadsheet has to have specific column names present in the first row (though order is not important).
\end{itemize}

\subsection*{Required columns}
There are several columns that need to be included in each spreadsheet
that also contains phenotypic data.  These correspond broadly to the experimental
treatments, locations of experiment, identity of the plant (and its
parent) and anecdotal comments about that particular plant.

These columns need data.  If they are left blank, it makes it hard to
perform all the cool analyses that these data will allow.  Please try
very hard to enter accurate, reasonable values for each plant.

Here is a list of columns with some descriptions of their contents

\begin{description}

\item[accession] The name of the line.  Most of the unPAK line ids are
  in the form of '\texttt{SALK\_nnnnnnC}' or '\texttt{CS70000}'

\item[expt.id] The name of the experiment.  Usually these are agreed
  upon across institutions or within a CURE or set of CUREs.  See \anl{the list of experiments}{http://107.170.89.221:3838/listexp/}

\item[institution] The name of the institution. See \anl{the list of institutions}{http://107.170.89.221:3838/listinstitution/}
  
\item[facility]  The ID of the growth chamber or greenhouse See \anl{the list of facilities}{http://107.170.89.221:3838/listfacility/}

\item[expt.plantnum] the unique number given to this plant during the experiment

\item[flat] the flat it was grown in

\item[row] the row it was grown in

\item[column] the column ...

\item[date] date that the phenotype was finalized

\item[investigator] 
  \item[parent.id] The id for the parent of the plant.  These are
  constructed from the institution, experiment name and the plantnum
  of the parent during that experiment.  

\end{description}

\subsection*{Phenotypes}
\emph{At least one column specifying a numeric phenotype is required.}  If
there are multiple columns with numeric phenotypic data, they are all
used.

The name of the column should correspond to existing phenotypes in the database 
See \anl{the list of phenotypes currently in the database}{http://107.170.89.221:3838/listpheno/}.

If the phenotype does not exist in the db currently, then an error is
generated.  

This will happen when you have a phenotype new to unpak.  In this case
email \texttt{unpak.database@gmail.com} with the information about
your new phenotype.  This information must include all of the
information for your new phenotype that corresponds to current entries
in the \anl{phenotype table}{http://107.170.89.221:3838/listpheno/}.

\emph{Please make sure that your new phenotype really is different
  than an existing one.  One great strength of unPAK is the fact that we
  can compare phenotypes across experiments.  If your phenotype has a
  different name, but measures the same thing as one already in the
  db, we will not be able to take full advantage of your hard work.}

\subsection*{Optional columns}

These columns are not required, but information in them will be recorded.
\begin{description}
\item[comment] The is a comment that corresponds to this plant.  It might describe some specific problem with the plant or its phenotypes.
\end{description}

\subsection*{Questions or requests for changes to db}
email \texttt{unpak.database@gmail.com}



%
%
%
% Local Variables: 
% TeX-master: "upload-format"
% End:

